apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: practicerole
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployment"]
  verbs: ["get", "watch", "list"]
